from typing import Protocol, Any


class Comparable(Protocol):
    
    def __eq__(self, value:Any) -> bool:...
    
    def __lt__(self, other:Any) -> bool:...
    
    def __gt__(self, other:Any) -> bool:...

    def __ge__(self, other:Any) -> bool:...
    
    def __le__(self, other:Any) -> bool:...
